[build]
  command = "cd nextjs && npm install && npm run build"
  publish = "nextjs/out"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Catch-all redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 